processed 26 tasks

init:
validator_0: object(0,0)

task 1, lines 7-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5563200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 32:
//# view-object 0,0
Owner: Account Address ( validator_0 )
Version: 1
Contents: iota_system::staking_pool::StakedIota {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(0,0),
        },
    },
    pool_id: iota::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 0u64,
    principal: iota::balance::Balance<iota::iota::IOTA> {
        value: 1500000000000000u64,
    },
}

task 5, line 34:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 36:
//# view-object 3,0
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 38:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 40:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, computation_cost_burned: 3000000, storage_cost: 10138400, storage_rebate: 1960800, non_refundable_storage_fee: 0 }}

task 9, line 42:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 44:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: CB9R4MWVWhxipXjFBF8mHyCXxW4EGGvuW4wJj5dNAnDT,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 46-51:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 53:
//# create-checkpoint
Checkpoint created: 11

task 13, line 55:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 57-62:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 64-69:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-iota-rpc-version": "0.11.0-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 0.11.0-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 71:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 73-76:
//# advance-epoch
Epoch advanced: 6

task 18, lines 78-93:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0xc5547cb57ae1630fc7cf34a29f6ec145e58adabd0311ce2792266d8976e795be",
              "digest": "8vkyLhyKuqv4Cb8QNafGWkL8s44B6RPSzSoVAMCLLaT2",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 95-150:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0xc5547cb57ae1630fc7cf34a29f6ec145e58adabd0311ce2792266d8976e795be",
              "digest": "8vkyLhyKuqv4Cb8QNafGWkL8s44B6RPSzSoVAMCLLaT2",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x0084a2538454a4bfeb925217fa95fffa045a38335d282ca5530d9840e876d0da",
              "digest": "23zDGWdD79fCBpxNtWTcDnJhV38bXFiB3GAkunm1b56g",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x0bbf08b0544c2bca37dd2df7a17be39750d42da6f85b8a51532c7cf80187081d",
              "digest": "9XtvG1yWpC5XK3bapyZvh9VUhwDD3fHk4bxxQ3tgnaPU",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x4a76e29f2f24ecc99efb7b2f957e8c02f2da75607f165cc0fdf207c351d84525",
              "digest": "Exui5TbuC6ULRSuWw61a2uPQ75iUHrrUtpkTHFgvynna",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x65671988f83d32f85536873463400433e8d96bfd1ec5290acbd0b045bbe13b5a",
              "digest": "8HHvyHTSNd3wk6vcKeFYkvAQodGNRN2XGfmv47t9rNUP",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x69b923df83a37826d09c5e792df93e74ec626012fe5ada7576f7338362ddc90a",
              "digest": "ArdhQjom6J58yB2hyoZQkzVE4ocRKvDm8FKam7fcNM8f",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x6eaef7d89547478bcfe78c9427d9c81ed9202f6cb2c1ab0ae5adb711d9891c11",
              "digest": "CdaxhhWZ7YZx5fJfWH8d2RMgAn5bMjzSXtaYqg2C3wps",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x9e69c660d4dc8e176f2874922a24bb90184b372dc04f73a48fc87ce2b07c954b",
              "digest": "Eg2kC6UNeGg9D8gGSSxzzvSXbZ1REW9VWqZx8E8myQFg",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x9f121e5b846bfbcd6c8b2bcb29f0250c43e8cdbd05f54b8189e9e47c34e28ad7",
              "digest": "9v8gB9WuXwdtL6r8Ktu9FW84A2yvkdu1QGFwzsDYySfg",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xa4ba1aa7137d5c35b8ab987eaf40535462f10840208ccb3cb90820e7a26bc427",
              "digest": "AgLAqPqjKbraBM8io7w3iqxZ2t9biS3D9aR42dQXLwXU",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xbd20e8340a2bf69e0884f7a6c35a7ff89b81be3ee90e0453573bd12121e1c0c5",
              "digest": "41XUuFssKpqCmFC8TyCB21Dn3qmv8L44y3KuVNpgsdhY",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xbd83e4bcdb7b40f0ade263fa26531af46940740a2a4b4a615829060e9f6e0331",
              "digest": "22kkXiTjUJX7gX26P92CBq7HySLsasC6pSGbK1TbkBe7",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xea204146efbdcb2d3245464e7d50130b72c51788e2323ebba7a03109fd94a48a",
              "digest": "CfnwEHv4Z9uN9DWU9J6qdKqvT6i7kfTEMbKrEYX4aDzU",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 152-168:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
    }
  }
}

task 21, lines 170-176:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 178:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, computation_cost_burned: 999000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 23, line 180:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 24, line 182:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, computation_cost_burned: 235000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 25, lines 184-189:
//# run-graphql
Response: {
  "data": {
    "serviceConfig": {
      "availableVersions": [
        "0.11"
      ]
    }
  }
}
