processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10495600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3017200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xd3bc48d6d11e058fc33ae8c04f042fd9d74ea5aa825accd00b67d0dd3067bc0f::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  121,
                                  57,
                                  232,
                                  198,
                                  159,
                                  189,
                                  94,
                                  252,
                                  78,
                                  70,
                                  99,
                                  92,
                                  146,
                                  86,
                                  214,
                                  74,
                                  146,
                                  204,
                                  107,
                                  25,
                                  216,
                                  102,
                                  43,
                                  218,
                                  14,
                                  156,
                                  215,
                                  42,
                                  73,
                                  183,
                                  146,
                                  71
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  121,
                                  57,
                                  232,
                                  198,
                                  159,
                                  189,
                                  94,
                                  252,
                                  78,
                                  70,
                                  99,
                                  92,
                                  146,
                                  86,
                                  214,
                                  74,
                                  146,
                                  204,
                                  107,
                                  25,
                                  216,
                                  102,
                                  43,
                                  218,
                                  14,
                                  156,
                                  215,
                                  42,
                                  73,
                                  183,
                                  146,
                                  71
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      121,
                                      57,
                                      232,
                                      198,
                                      159,
                                      189,
                                      94,
                                      252,
                                      78,
                                      70,
                                      99,
                                      92,
                                      146,
                                      86,
                                      214,
                                      74,
                                      146,
                                      204,
                                      107,
                                      25,
                                      216,
                                      102,
                                      43,
                                      218,
                                      14,
                                      156,
                                      215,
                                      42,
                                      73,
                                      183,
                                      146,
                                      71
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x7939e8c69fbd5efc4e46635c9256d64a92cc6b19d8662bda0e9cd72a49b79247",
                          "f0": "0x7939e8c69fbd5efc4e46635c9256d64a92cc6b19d8662bda0e9cd72a49b79247",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x7939e8c69fbd5efc4e46635c9256d64a92cc6b19d8662bda0e9cd72a49b79247"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  205,
                                  100,
                                  194,
                                  237,
                                  68,
                                  194,
                                  213,
                                  212,
                                  46,
                                  62,
                                  166,
                                  234,
                                  155,
                                  160,
                                  106,
                                  46,
                                  67,
                                  19,
                                  25,
                                  11,
                                  204,
                                  55,
                                  22,
                                  168,
                                  65,
                                  59,
                                  13,
                                  142,
                                  9,
                                  87,
                                  1,
                                  67
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995982800"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xcd64c2ed44c2d5d42e3ea6ea9ba06a2e4313190bcc3716a8413b0d8e09570143",
                          "balance": {
                            "value": "299999995982800"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
