processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10495600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3017200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  59,
                                  116,
                                  183,
                                  29,
                                  234,
                                  75,
                                  112,
                                  115,
                                  149,
                                  251,
                                  223,
                                  178,
                                  143,
                                  225,
                                  97,
                                  33,
                                  81,
                                  6,
                                  211,
                                  43,
                                  108,
                                  167,
                                  58,
                                  114,
                                  185,
                                  42,
                                  18,
                                  188,
                                  62,
                                  129,
                                  252,
                                  42
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995982800"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x3b74b71dea4b707395fbdfb28fe161215106d32b6ca73a72b92a12bc3e81fc2a",
                          "balance": {
                            "value": "299999995982800"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x28060471e8b4d633abe6eb1b67b4d4d2c01d040a305cd7e536af21bb1afa5a98::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  166,
                                  54,
                                  192,
                                  136,
                                  46,
                                  239,
                                  97,
                                  202,
                                  249,
                                  187,
                                  151,
                                  43,
                                  228,
                                  235,
                                  199,
                                  4,
                                  221,
                                  130,
                                  163,
                                  169,
                                  168,
                                  23,
                                  129,
                                  82,
                                  116,
                                  89,
                                  73,
                                  221,
                                  133,
                                  197,
                                  244,
                                  117
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  166,
                                  54,
                                  192,
                                  136,
                                  46,
                                  239,
                                  97,
                                  202,
                                  249,
                                  187,
                                  151,
                                  43,
                                  228,
                                  235,
                                  199,
                                  4,
                                  221,
                                  130,
                                  163,
                                  169,
                                  168,
                                  23,
                                  129,
                                  82,
                                  116,
                                  89,
                                  73,
                                  221,
                                  133,
                                  197,
                                  244,
                                  117
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      166,
                                      54,
                                      192,
                                      136,
                                      46,
                                      239,
                                      97,
                                      202,
                                      249,
                                      187,
                                      151,
                                      43,
                                      228,
                                      235,
                                      199,
                                      4,
                                      221,
                                      130,
                                      163,
                                      169,
                                      168,
                                      23,
                                      129,
                                      82,
                                      116,
                                      89,
                                      73,
                                      221,
                                      133,
                                      197,
                                      244,
                                      117
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xa636c0882eef61caf9bb972be4ebc704dd82a3a9a8178152745949dd85c5f475",
                          "f0": "0xa636c0882eef61caf9bb972be4ebc704dd82a3a9a8178152745949dd85c5f475",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xa636c0882eef61caf9bb972be4ebc704dd82a3a9a8178152745949dd85c5f475"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
