processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10495600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3017200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x082d19c7f756071d61477905951cacbe98480a8004f739b361e2cdc9a7d1c804::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  97,
                                  45,
                                  147,
                                  188,
                                  20,
                                  186,
                                  250,
                                  162,
                                  243,
                                  169,
                                  30,
                                  191,
                                  17,
                                  72,
                                  44,
                                  9,
                                  233,
                                  194,
                                  166,
                                  66,
                                  43,
                                  137,
                                  119,
                                  59,
                                  22,
                                  49,
                                  19,
                                  150,
                                  251,
                                  91,
                                  177,
                                  147
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  97,
                                  45,
                                  147,
                                  188,
                                  20,
                                  186,
                                  250,
                                  162,
                                  243,
                                  169,
                                  30,
                                  191,
                                  17,
                                  72,
                                  44,
                                  9,
                                  233,
                                  194,
                                  166,
                                  66,
                                  43,
                                  137,
                                  119,
                                  59,
                                  22,
                                  49,
                                  19,
                                  150,
                                  251,
                                  91,
                                  177,
                                  147
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      97,
                                      45,
                                      147,
                                      188,
                                      20,
                                      186,
                                      250,
                                      162,
                                      243,
                                      169,
                                      30,
                                      191,
                                      17,
                                      72,
                                      44,
                                      9,
                                      233,
                                      194,
                                      166,
                                      66,
                                      43,
                                      137,
                                      119,
                                      59,
                                      22,
                                      49,
                                      19,
                                      150,
                                      251,
                                      91,
                                      177,
                                      147
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x612d93bc14bafaa2f3a91ebf11482c09e9c2a6422b89773b16311396fb5bb193",
                          "f0": "0x612d93bc14bafaa2f3a91ebf11482c09e9c2a6422b89773b16311396fb5bb193",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x612d93bc14bafaa2f3a91ebf11482c09e9c2a6422b89773b16311396fb5bb193"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  165,
                                  79,
                                  71,
                                  208,
                                  26,
                                  126,
                                  8,
                                  87,
                                  188,
                                  217,
                                  32,
                                  152,
                                  87,
                                  237,
                                  166,
                                  11,
                                  50,
                                  200,
                                  80,
                                  147,
                                  196,
                                  116,
                                  84,
                                  223,
                                  240,
                                  244,
                                  26,
                                  144,
                                  62,
                                  147,
                                  205,
                                  240
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995982800"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xa54f47d01a7e0857bcd9209857eda60b32c85093c47454dff0f41a903e93cdf0",
                          "balance": {
                            "value": "299999995982800"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
